using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Globalization;
using System.Text;

namespace Telani.SourceGenerator;

/// <summary>
/// A generator to add a class containing the build date to the output.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class DateSourceGenerator : IIncrementalGenerator
{

    private readonly record struct BuildDateClassEntry(string ClassNamespace, string ClassName);

    private static StringBuilder GenerateSource(string dateString, BuildDateClassEntry entry)
    {
        return new(@"
using System;
using System.Globalization;

namespace " + entry.ClassNamespace + @"
{
    internal static partial class " + entry.ClassName + @"
    {
        internal static DateTime GetBuildDate() 
        {
            return DateTime.ParseExact(""" + dateString + @""", ""d"", CultureInfo.InvariantCulture);
        }
    }
}");
    }

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var a = context.ParseOptionsProvider.Select(static (ab, cancel) => DateTime.UtcNow.ToString("d", CultureInfo.InvariantCulture));

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName("Telani.SourceGenerator.TelaniBuildDateAttribute",
                    predicate: static (node, _) => IsSyntaxTargetForGenerationQuick(node),
                    transform: static (context, _) => {
                        var className = context.TargetSymbol;
                        var classNamespace = className.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

                        return new BuildDateClassEntry(classNamespace, className.Name);
                    });

        context.RegisterSourceOutput(targets.Combine(a), static (productionContext, pair) =>
        {
            productionContext.AddSource("TelaniSourceGeneratorBuildDate.g.cs", GenerateSource(pair.Right, pair.Left).ToString());
        });

        context.RegisterPostInitializationOutput(static c =>
        {
            c.AddEmbeddedAttributeDefinition();
            c.AddSource("TelaniBuildDateAttribute.g.cs", ReadAttributesFile());
        });
    }

    private static bool IsSyntaxTargetForGenerationQuick(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax)
        {
            return false;
        }
        return true;
    }

    private static string ReadAttributesFile()
    {
        return @"
// <auto-generated/>

#nullable enable

// Suppress warnings about unused parameters in generated code
#pragma warning disable CS9113

using System.Globalization;

namespace Telani.SourceGenerator;

/// <summary>
/// This attribute generates a build date string.
/// </summary>
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
[AttributeUsage(AttributeTargets.Class)]
internal sealed class TelaniBuildDateAttribute() : Attribute
{

}
";
    }
}
