using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Globalization;
using System.Text;

namespace Telani.SourceGenerator;

/// <summary>
/// A generator to add a class containing the build date to the output.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class DateSourceGenerator : IIncrementalGenerator
{

    private readonly record struct BuildDateClassEntry(string ClassNamespace, string ClassName, Accessibility Accessibility, bool IsStatic, bool IsAbstract, bool IsSealed);

    private static string GenerateAccessibilityString(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Internal => "internal",
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal",
        };
    }

    private static SourceWriter GenerateSourceHeader(BuildDateClassEntry entry)
    {
        var sb = GenerateSourceFileHeader(entry);
        sb.WriteLine("internal static partial DateTime GetBuildDate();");
        sb.WriteEndBlock();
        return sb;
    }

    private static SourceWriter GenerateSourceFileHeader(BuildDateClassEntry entry)
    {
        var sw = new SourceWriter();
        sw.WriteLine(@"// <auto-generated/>");
        sw.WriteLine();
        sw.WriteLine("#nullable enable");
        sw.WriteLine();
        sw.WriteLine("using System;");
        sw.WriteLine("using System.Globalization;");
        sw.WriteLine();
        sw.WriteLine("namespace " + entry.ClassNamespace + @";");
        sw.WriteLine();
        sw.WriteLine(GenerateAccessibilityString(entry.Accessibility) + (entry.IsStatic ? " static" : "") + (entry.IsAbstract ? " abstract" : "") + (entry.IsSealed ? " sealed" : "") + " partial" + " class " + entry.ClassName);
        sw.WriteStartBlock();
        return sw;
    }

    private static SourceWriter GenerateSource(string dateString, BuildDateClassEntry entry)
    {
        var sb = GenerateSourceFileHeader(entry);
        sb.WriteLine("internal static partial DateTime GetBuildDate()");
        sb.WriteStartBlock();
        sb.WriteLine(@"return DateTime.ParseExact(""" + dateString + @""", ""d"", CultureInfo.InvariantCulture);");
        sb.WriteEndBlock();
        sb.WriteEndBlock();

        return sb;
    }

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // ParseOptionsProvider is a provider that rarely changes, so we use that to generate the date as rarely as possible.
        // This might not get updated every day, but it seems the cache is not persisted between VS sessions, so at least every time VS is restarted it should get the current date.
        // Building in CI always gets the current date as well, of course.
        var a = context.ParseOptionsProvider.Select(static (ab, cancel) => DateTime.UtcNow.ToString("d", CultureInfo.InvariantCulture));

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName("Telani.SourceGenerator.TelaniBuildDateAttribute",
                    predicate: static (node, _) => IsSyntaxTargetForGenerationQuick(node),
                    transform: static (context, _) => {

                        // TODO: Check that the class is partial
                        // TODO: Base classes and generics are not supported here, so either we could add that or we could issue diagnostics if they are used.
                        var className = context.TargetSymbol;
                        var isStatic = className.IsStatic;
                        var isAbstract = className.IsAbstract;
                        var isSealed = className.IsSealed;
                        var visibility = className.DeclaredAccessibility;
                        var classNamespace = className.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

                        return new BuildDateClassEntry(classNamespace, className.Name, visibility, isStatic, isAbstract, isSealed);
                    });

        // Because the date/time changes all the time, we intend to produce only a partial source file with the method signature at first.
        context.RegisterSourceOutput(targets, static (productionContext, entry) =>
        {
            productionContext.AddSource("TelaniSourceGeneratorBuildDate.g.cs", GenerateSourceHeader(entry).ToSourceText());
        });

        // The RegisterImplementationSourceOutput is not really functional in rosly as of now, but it is intended to only run at build time and not in the IDE.
        // So this would be perfect to fill in the implementation of the method, containing the actual build date/time.
        // See: https://github.com/dotnet/roslyn/issues/77288
        // See: https://github.com/dotnet/roslyn/issues/78108

        // Currently this gets called the same way that RegisterSourceOutput does, so we prevent it from generating for every keystroke by using the ParseOptionsProvider above.
        // Once this method works as intended, this will only be called at build time so we can switch to context.CompilationProvider instead of using the ParseOptionsProvider and also include the time.
        context.RegisterImplementationSourceOutput(targets.Combine(a), static (productionContext, pair) =>
        {
            productionContext.AddSource($"TelaniSourceGeneratorBuildDate_Impl.g.cs", GenerateSource(pair.Right, pair.Left).ToSourceText());
        });

        context.RegisterPostInitializationOutput(static c =>
        {
            c.AddEmbeddedAttributeDefinition();
            var attribute = Helpers.ReadParameterlessAttributesFile("TelaniBuildDateAttribute", "This attribute generates a build date string.");
            c.AddSource("TelaniBuildDateAttribute.g.cs", attribute.ToSourceText());
        });
    }

    private static bool IsSyntaxTargetForGenerationQuick(SyntaxNode node)
    {
        // This is probably unnecessary, because the attribute has a usage attribute restricting it to classes only, but let's be safe.
        if (node is not ClassDeclarationSyntax)
        {
            return false;
        }
        return true;
    }

}
