namespace Telani.SourceGenerator;

internal static class Helpers
{
    internal static SourceWriter ReadParameterlessAttributesFile(string attributeName, string description, AttributeTargets attributeTarget = AttributeTargets.Class)
    {
        var sb = new SourceWriter();
        sb.WriteLine(@"// <auto-generated/>

#nullable enable

// Suppress warnings about unused parameters in generated code.
#pragma warning disable CS9113

using System.Globalization;

namespace Telani.SourceGenerator;

/// <summary>
/// " + description + @"
/// </summary>
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
[AttributeUsage(AttributeTargets." + attributeTarget.ToString() + @")]
internal sealed class " + attributeName + @"() : Attribute
{

}");
        return sb;
    }
}
