using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace Telani.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class MiniAPIRouter : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var routes = context.SyntaxProvider.ForAttributeWithMetadataName("Telani.SourceGenerator.TelaniRouteAttribute",
                    predicate: static (node, _) => IsSyntaxTargetForGenerationQuick(node),
                    transform: static (syntaxContext, _) => ((ClassDeclarationSyntax)syntaxContext.TargetNode, syntaxContext.SemanticModel))
                    .Select(static (a, _) => PrepareRoute(a.Item1, a.SemanticModel));

        context.RegisterSourceOutput(routes.Collect(), Execute);

        context.RegisterPostInitializationOutput(static c =>
        {
            c.AddEmbeddedAttributeDefinition();
            c.AddSource("TelaniRouteAttributes.g.cs", ReadAttributesFile());
        });
    }

    private readonly record struct RouteEntry(string Name, string ClassNamespace, string RequestRoute, HttpMethod Method, string RequestRegex);

    private static RouteEntry PrepareRoute(ClassDeclarationSyntax i, SemanticModel semModel)
    {
        /*if (!Debugger.IsAttached)
        {
            Debugger.Launch();
            Debugger.Break();
        }*/
        var className = i.Identifier.ValueText;
        var classNamespace = semModel.GetDeclaredSymbol(i)?.ContainingNamespace?.ToDisplayString() ?? "";
        string requestRoute = string.Empty;
        string requestRegex = string.Empty;
        HttpMethod requestMethod = HttpMethod.Get;

        foreach (var attributesOnClass in i.AttributeLists)
        {
            foreach (var att in attributesOnClass.Attributes)
            {
                var name = (att.Name as SimpleNameSyntax)?.Identifier.ValueText;
                if (name == "TelaniRoute" || name == "TelaniRouteAttribute")
                {
                    var args = att.ArgumentList?.Arguments.FirstOrDefault()?.Expression as LiteralExpressionSyntax;
                    if (args is not null)
                    {
                        requestMethod = ParseMethod(args.Token.Text.Trim('"'));
                    }
                    var arg2 = att.ArgumentList?.Arguments.Last()?.Expression as LiteralExpressionSyntax;
                    if (arg2 is not null)
                    {
                        requestRoute = arg2.Token.Text;

                        var regex = new Regex(@"{(\w+)}");
                        requestRegex = regex.Replace(arg2.Token.Text, @"(?<$1>[^/]+)");                        
                    }
                }
            }
        }

        return new RouteEntry(className, classNamespace, requestRoute, requestMethod, requestRegex);
    }

    // In newer dotnet this is built-in.
    private static HttpMethod ParseMethod(string text) => text switch
    {
        "PUT" => HttpMethod.Put,
        "DELETE" => HttpMethod.Delete,
        "GET" => HttpMethod.Get,
        "POST" => HttpMethod.Post,
        "TRACE" => HttpMethod.Trace,
        "OPTIONS" => HttpMethod.Options,
        "HEAD" => HttpMethod.Head,
        _ => throw new ArgumentException("Invalid method type")
    };

    public static string ToTitleCase(string title) => CultureInfo.InvariantCulture.TextInfo.ToTitleCase(title.ToLowerInvariant());

    private static void Execute(SourceProductionContext context, ImmutableArray<RouteEntry> inputs)
    {
        if (!inputs.Any())
        {
            return;
        }
        var extension = new SourceWriter();
        extension.WriteLine("// <auto-generated/>");
        extension.WriteLine();
        extension.WriteLine("#nullable enable");
        extension.WriteLine();
        extension.WriteLine("using System.Net.Http;");
        extension.WriteLine("using System.Text.RegularExpressions;");
        extension.WriteLine();

        foreach (var input in inputs)
        {
            extension.WriteLine($"namespace {input.ClassNamespace}");
            extension.WriteStartBlock();
            extension.WriteLine($"/// <summary>");
            extension.WriteLine($"/// </summary>");
            extension.WriteLine($"public partial class {input.Name}");
            extension.WriteStartBlock();
            extension.WriteLine("/// <summary>");
            extension.WriteLine("/// The route pattern that this route matches, including any placeholders.");
            extension.WriteLine("/// </summary>");
            extension.WriteLine($"public override string Path => {input.RequestRoute};");
            extension.WriteLine();
            extension.WriteLine("/// <summary>");
            extension.WriteLine("/// The http verb that this route accepts.");
            extension.WriteLine("/// </summary>");
            extension.WriteLine($"public override HttpMethod Method => HttpMethod.{ToTitleCase(input.Method.Method)};");
            extension.WriteLine();
            extension.WriteLine("/// <summary>");
            extension.WriteLine("/// This is a pre-generated regex to help with matching this route pattern.");
            extension.WriteLine("/// </summary>");
            extension.WriteLine($"internal override Regex RequestRegex => new Regex($\"^{input.RequestRegex.Trim('"')}/?$\", RegexOptions.IgnoreCase);");
            extension.WriteEndBlock();
            extension.WriteEndBlock();
        }
        context.AddSource($"RouteExtensions.g.cs", extension.ToSourceText());
    }

    private static bool IsSyntaxTargetForGenerationQuick(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax)
        {
            return false;
        }
        return true;
    }

    private static string ReadAttributesFile()
    {
        return @"// <auto-generated/>

#nullable enable

// Suppress warnings about unused parameters in generated code
#pragma warning disable CS9113

using System.Globalization;

namespace Telani.SourceGenerator;

/// <summary>
/// This class implements a route for a Rest-API.
/// </summary>
/// <param name=""Method"">The http verb that this route accepts, for example GET, POST etc.</param>
/// <param name=""RequestRoute"">The route pattern that this route matches, can contain placeholders. An example would be: /test/{id}</param>
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
[AttributeUsage(AttributeTargets.Class)]
internal sealed class TelaniRouteAttribute(string Method, string RequestRoute) : Attribute
{

}
";
    }
}
