<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <ImplicitUsings>enable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IncludeBuildOutput>false</IncludeBuildOutput>
	<IsRoslynComponent>true</IsRoslynComponent>
  </PropertyGroup>

  <PropertyGroup>
	<!-- nuget -->
    <PackageId>Telani.SourceGenerator</PackageId>
	<PackageProjectUrl>https://github.com/telani-app/telani.sourcegenerator</PackageProjectUrl>
    <Authors>telani-Team</Authors>
    <Company>gb&amp;t Gebäudebestand und Technik GmbH</Company>
    <Product>Telani.SourceGenerator</Product>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<RepositoryUrl>https://github.com/telani-app/telani.sourcegenerator</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<IncludeSymbols>false</IncludeSymbols>
	<DebugType>Embedded</DebugType>
	<EmbedUntrackedSources>true</EmbedUntrackedSources>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

    <PropertyGroup Condition="'$(CI)' == 'true'">
	    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

	<!--
      https://github.com/dotnet/roslyn/issues/52017#issuecomment-1046216200
      This automatically adds explicit and transient dependencies so that they are available at the time the generator is executed. 
  -->
  <Target Name="AddGenerationTimeReferences" AfterTargets="ResolvePackageDependenciesForBuild">
    <ItemGroup>
      <None Include="@(ResolvedCompileFileDefinitions)" Pack="true" PackagePath="analyzers/dotnet/cs" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" PrivateAssets="all" />
	<PackageReference Include="Nerdbank.GitVersioning" Version="3.8.118" PrivateAssets="all" />
	<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>
</Project>
